### ISSUE TITLE
Request To Add Start Screen Recording To Quick Buttons/Notification Centre

### ISSUE THREAD

**Issue by knoddix** [yakovlevegor/DroidRec#10]
Hey Guys

I love the simplicity of the app, I see that's the beauty of it, that being said is there any possibility of adding a trigger to start screen recording from within the notification centre pull down?

Kind Regards
Adrian

**Comment by yakovlevegor** [comment]
I don't see why not. I'll try implementing it in the next version.

**Comment by knoddix** [comment]
> I don't see why not. I'll try implementing it in the next version.

Thanks Egor, I really appreciate your effort.
