### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by xmha97** [yakovlevegor/DroidRec#14]
I installed the new version from F-Droid but it won't install!
Is Android 12 not enough?

![Screenshot_2022-11-04-00-47-33-974_org.fdroid.fdroid.jpg](https://user-images.githubusercontent.com/23485114/199836269-a03d03f1-ef54-4d4c-821c-366a01853479.jpg)

**Comment by yakovlevegor** [comment]
The update [1.5](https://github.com/yakovlevegor/DroidRec/releases/tag/v1.5) came out yesterday. Please note that F-Droid has delays in updating their repositories.
