### ISSUE TITLE
Adaptive Icon

### ISSUE THREAD

**Issue by xmha97** [yakovlevegor/DroidRec#15]
Please add an adaptive icon.

![Screenshot_2022-11-04-00-50-21-603_com.microsoft.launcher.jpg](https://user-images.githubusercontent.com/23485114/199836486-528e8683-e958-445a-b4f0-ee0183f5f534.jpg)

**Comment by yakovlevegor** [comment]
Adaptive icon is added for the next version.

**Comment by yakovlevegor** [comment]
Version [1.6](https://github.com/yakovlevegor/DroidRec/releases/tag/v1.6) is out, closing.

**Comment by xmha97** [comment]
Thanks but please improve it. (like the picture below):
![image](https://user-images.githubusercontent.com/23485114/202060017-30faa0a8-7539-4547-91b0-f06843ec908f.png)

**Comment by yakovlevegor** [comment]
I don't get it. Please specify the icon.

**Comment by xmha97** [comment]
![image](https://user-images.githubusercontent.com/23485114/202060267-32db37d4-0d4a-46aa-abb4-0fd86374f56b.png)
Please resize the content of the icon.

**Comment by yakovlevegor** [comment]
Here, Version [1.7](https://github.com/yakovlevegor/DroidRec/releases/tag/v1.7). The icon is fixed.
