### ISSUE TITLE
Proofreading

### ISSUE THREAD

**Issue by moriel5** [yakovlevegor/DroidRec#19]
First of all, thank you very much for your app, it works extremely well.

And now to business. I don't intend to come off as rude, I'm just a perfectionist, however I had noticed that the Hebrew README is a bit hard to understand, so I wondered whether you'd be interested in me proofreading whatever is in Hebrew in this GitHub repository?

I already translate a few pieces of software to Hebrew (such as MiXplorer or the Budgie DE) when I have the time, if you wish to see to what standards I uphold myself.

**Comment by yakovlevegor** [comment]
To be honest I started learning Hebrew about 3 years ago, and I know it on some very primitive level. So yeah, proofreading everything would be an excellent idea.

**Comment by moriel5** [comment]
Well, that is already a great start, although I can certainly say that since Hebrew is constructed differently than English (and I presume also Russian, I'll have to ask my parents about that, as I do not understand more than a few words in Russian, much to my grandmother's chagrin), focusing on the syntax at this stage will certainly help you improve.

Bli neder, I'll probably start either on Motzaei Shabbat or sometime during the following daytime (Sunday), as Shabbat is arriving in a few minutes.

By the way, just out of interest, but what influenced you to learn Hebrew? Family?

**Comment by yakovlevegor** [comment]
>but what influenced you to learn Hebrew

Been just interested, that's all. I'm not religious. Finding open Hebrew dictionaries on the web proves to be a real pain. Found a couple of learning books on Internet Archive, been trying to read them. And of course I've started from a learning book in russian.

**Comment by moriel5** [comment]
I'm sorry about the delay, chores and unexpected real life events have taken the time away.
Hopefully, I should be able to start in a few hours.

And that is certainly true, I too have been searching (mainly to help certain FOSS apps), without any success. Only paid closed source dictionaries.

**Comment by yakovlevegor** [comment]
Just realized why Hebrew translation is not shown on F-Droid or in the app. Java uses deprecated language codes for Hebrew and several other languages. In the following update it will be fixed and translation will become visible.

**Comment by yakovlevegor** [comment]
The repository migrates to GitLab, new page for your issue is: https://gitlab.com/egoroyakovlev/DroidRec/-/issues/19
