### ISSUE TITLE
Accessibility issues in GUIs

### ISSUE THREAD

**Issue by Kazaf123** [yakovlevegor/DroidRec#26]
**Description**
This is a bug report about components that have accessibility issues within the GUI of such an App.
**Content**
After I applied my proposed tool to detect the content page, I discovered the following components which have the accessibility issues, and I sincerely struggled you could repair these issues so that the visually impaired users would use this App more conveniently.
In practical, each component in the index page suffer from narrow intervals, I would appreciate it If the interval of these components can be enlarged.

**Comment by yakovlevegor** [comment]
I don't follow what you mean by narrow intervals. It this related to activity elements' position and scale?

**Comment by Kazaf123** [comment]
yes，I mean it  @reply+AKQKZCJ52YPXYXLGKST2RMOBSBK5FEVBNHHFOV6HGE  



---- Replied Message ----
| From | Egor ***@***.***> |
| Date | 11/27/2022 16:44 |
| To | ***@***.***> |
| Cc | Mengxi ***@***.***>***@***.***> |
| Subject | Re: [yakovlevegor/DroidRec] Accessibility issues in GUIs (Issue #26) |

I don't follow what you mean by narrow intervals. It this related to activity elements' position and scale?

**Comment by yakovlevegor** [comment]
Okay. I get it, I should use "sp" when scaling text and other items in an activity.

**Comment by yakovlevegor** [comment]
No, only for fonts. Other elements need to use "dp" instead. Alright, working on it.

**Comment by Kazaf123** [comment]
thank you vey much



---- Replied Message ----
| From | Egor ***@***.***> |
| Date | 11/27/2022 17:20 |
| To | ***@***.***> |
| Cc | Mengxi ***@***.***>***@***.***> |
| Subject | Re: [yakovlevegor/DroidRec] Accessibility issues in GUIs (Issue #26) |

No, only for fonts. Other elements need to use "dp" instead. Alright, working on it.

**Comment by yakovlevegor** [comment]
Done. Will be included in a new version.

**Comment by yakovlevegor** [comment]
Version [2.2](https://github.com/yakovlevegor/DroidRec/releases/tag/v2.2) is out. The fix is in the latest release.
