### ISSUE TITLE
Notification buttons

### ISSUE THREAD

**Issue by xmha97** [yakovlevegor/DroidRec#27]
Please add some buttons on finish notification.

Like this:
![IMG_20221129_005548_163.jpg](https://user-images.githubusercontent.com/23485114/204384652-8fa5504a-ea50-44fa-a206-d523df456f22.jpg)

Current:
![Screenshot_2022-11-29-00-56-40-301_com.miui.home.jpg](https://user-images.githubusercontent.com/23485114/204384671-fb647b1d-664e-40e9-ab5e-b07d3cc91133.jpg)

**Comment by yakovlevegor** [comment]
Actually pressing on the notification should open the file in gallery, but I just noticed it's defective, so I fixed it. Gonna add buttons too.

**Comment by xmha97** [comment]
Thanks.

**Comment by yakovlevegor** [comment]
Version [2.3](https://github.com/yakovlevegor/DroidRec/releases/tag/v2.3) is out, the fix is in the latest release.

**Comment by xmha97** [comment]
Thanks.
