### ISSUE TITLE
Increase the quality and productivity of the application

### ISSUE THREAD

**Issue by AI-IMED** [yakovlevegor/DroidRec#29]
Best open source screen recording app for Android, but I wonder:

  - Can you provide an option within the application to record clicks instead of activating it from the developers mode every time.
  - Can you make the floating control not appear in the recording regardless of the opacity
  
  Thanks

**Comment by yakovlevegor** [comment]
>Can you provide an option within the application to record clicks

No, I can't. A duplicate of #21.

>Can you make the floating control not appear in the recording

Yes, you can disable them in settings.
