### ISSUE TITLE
Issue with pausing the recording / rotating

### ISSUE THREAD

**Issue by Roshi617** [yakovlevegor/DroidRec#32]
Upon resuming the recording after pausing, it doesn't create a second video file. Same thing happens when I rotate my screen, it restarts the recording but doesn't make a second video file.

I'm on Android 11, using the latest version of the app from F-Droid. Not sure what kind of info you'll need. Just let me know.

Thanks in advance

**Comment by yakovlevegor** [comment]
It's already in the main branch, just not released yet, as I'm fixing the #30 error. I'll close this when the release is out.

**Comment by Roshi617** [comment]
Alright. Sounds good.

Also I wanted to mention that the screen rotation issue I had is fixed with release version 2.3. It's just pausing makes the entire file 0 bytes (as mentioned in the other issue).

**Comment by yakovlevegor** [comment]
Version [2.4](https://github.com/yakovlevegor/DroidRec/releases/tag/v2.4) is out. Should be fixed now.

**Comment by Roshi617** [comment]
Alright so, pausing doesn't make the file 0 bytes now. However, pausing doesn't create a second video file. At least, not in my case. The video file just ends right when I tapped pause.

**Comment by yakovlevegor** [comment]
That's an Android 10+ issue. Working on fixing it.

**Comment by yakovlevegor** [comment]
The issue happens because of automatic fps detection. Try to set fps explicitly to 30 in settings, the error should vanish. I'm reversing native fps detection for the next version.

**Comment by yakovlevegor** [comment]
Version [2.5](https://github.com/yakovlevegor/DroidRec/releases/tag/v2.5) is out. The fix is in the latest release.

**Comment by Roshi617** [comment]
Still having the issue. Fps is set to 30.

**Comment by yakovlevegor** [comment]
Try choosing a different codec.

**Comment by yakovlevegor** [comment]
Version [2.7](https://github.com/yakovlevegor/DroidRec/releases/tag/v2.7) is out. The fix is in the latest release.

**Comment by yakovlevegor** [comment]
Version [2.8](https://github.com/yakovlevegor/DroidRec/releases/tag/v2.8) is out.

**Comment by Roshi617** [comment]
Yep, problem solved.
