### ISSUE TITLE
Notification button do not work after update.

### ISSUE THREAD

**Issue by EdieN** [yakovlevegor/DroidRec#34]
Title.
![Screenshot_20221209-150634_One UI Home.jpg](https://user-images.githubusercontent.com/81774413/206765369-031178a6-540a-44e3-85b8-58bbaeac5880.jpg)

**Comment by yakovlevegor** [comment]
Fixed! The release [2.9](https://github.com/yakovlevegor/DroidRec/releases/tag/v2.9) is out.
