### ISSUE TITLE
No storage permission although granted using file manager

### ISSUE THREAD

**Issue by billie80** [yakovlevegor/DroidRec#35]
I updated from 2.3 to 2.5 using the F-Droid release. After selecting a recording folder and allowing access using the file manager I tried to start a recording. However then I get the toast message: "Error:Storage permission required"

I guess this is related to commit https://github.com/yakovlevegor/DroidRec/commit/61deb1d352710b3734cd2131e053af7e69545bf8 which added FileProvider Support on Androd 9 and lower.

I am on Android 10 and with 2.3 I was asked for the recording folder which seemed to work. The recording aborted quickly but a 0 byte file was created in the folder. So writing to the folder worked.

I can not give information about other issue with the failed recording because I am stuck before.  Will open a new issue if this isn't fixed with newer releases.

Noticed that there is 2.9 already but I guess the storage issue is not adressed there.

**Comment by yakovlevegor** [comment]
Whoops. Wrong api version was specified in permissions check. New release would be in a sec.

**Comment by yakovlevegor** [comment]
Version [3.0](https://github.com/yakovlevegor/DroidRec/releases/tag/v3.0) is out. The issue should be fixed.

**Comment by billie80** [comment]
Works now. Thanks!
Also recording seens to work now!
