### ISSUE TITLE
Feature: Delay recording

### ISSUE THREAD

**Issue by billie80** [yakovlevegor/DroidRec#37]
Is it possible to add an option to delay the recording?
The App is always in the foreground in the beginning. An option to delay the recording would allow to bring it in the backround and wait for the notification pop up to disappear.

**Comment by yakovlevegor** [comment]
The recording can't start without a notification.

**Comment by billie80** [comment]
Yes this is why an option to delay the recording would be beneficial. There is time to bring the App in the background and wait for the notification pop up to disappear.

**Comment by yakovlevegor** [comment]
I think I could add a setting to suppress the popup, though you can do that explicitly from system settings.

**Comment by billie80** [comment]
I see but still the App itself is in the foreground if the recording starts. Probably it could minimise itself but a delay option would be useful in other cases as well, at least in my opinion.

**Comment by yakovlevegor** [comment]
It would be in foreground nevertheless. You can't start a countdown without displaying a notification.

**Comment by yakovlevegor** [comment]
You can suppress and make it appear collapsed, yes, but nothing more than that.

**Comment by billie80** [comment]
Currently I use AZ Screenrecorder and it has a feature called "Countdown before start". It overlays the countdown on the screen and then starts the recording. Nothing else appears execpt the obligatory notifaction about the screen being recorded. It also has floating controls from which the recording can be started. With DroidRec they only appaer after the recording is started.

**Comment by yakovlevegor** [comment]
The repository migrates to GitLab, new page for your issue is: https://gitlab.com/egoroyakovlev/DroidRec/-/issues/37
