### ISSUE TITLE
Audio Recording Still Does Not Work

### ISSUE THREAD

**Issue by Tracy-Howarth** [yakovlevegor/DroidRec#39]
Hi Egor !

I just downloaded DroidRec v2.5 from F-Droid, but it soon became apparent that upon screen recording, the audio is not captured.

However, DroidRec does record the microphone output.

Having read the thread at https://github.com/yakovlevegor/DroidRec/issues/16, audio recording has been an ongoing problem, which sadly hasn't been resolved.

I even tried a previous build where you specifically stated the "audio format" had been fixed (from https://github.com/yakovlevegor/DroidRec/issues/16#issuecomment-1332175873), yet despite this the audio stream was still not being recorded.

Hope this issue may finally been rectified.

Appreciate your work Egor, and your TorBridgesUpdater app sounds like an excellent idea. I have yet to give it try. 👍

**Comment by yakovlevegor** [comment]
You sure it doesn't work with the latest version (it's 3.1 already)?

**Comment by yakovlevegor** [comment]
Also, the issue #16 refers to microphone recording, not audio.

**Comment by yakovlevegor** [comment]
And what is your Android version?

**Comment by yakovlevegor** [comment]
Audio recording won't work for you if you have Android version below 10, because Android can't record system audio on these versions.

**Comment by Roshi617** [comment]
System audio recording doesn't work on my Android 11 with app version 3.1. I think this is what they were trying to say. I even tested on apps that target SDK >=29 and I get no audio. Microphone works just fine.

**Comment by yakovlevegor** [comment]
This is very weird, because for me it does work. Version 3.0 works fine?

**Comment by yakovlevegor** [comment]
Everything works fine on an emulator too, so I clearly can't test this one.

**Comment by yakovlevegor** [comment]
Oh, this is for audio-only recording. I see what you mean then. Yep, it doesn't work.

**Comment by yakovlevegor** [comment]
No, it does. It does work, even on an emulator. Well, this is just very strange.

**Comment by Roshi617** [comment]
No I think we both meant video + system audio recording. I will try version 3.0 but maybe there is a misunderstanding.

**Comment by Roshi617** [comment]
Yeah version 3.0 makes a 0 bytes video file.

**Comment by yakovlevegor** [comment]
I tried both - they all work for me, on a phone, on an emulator. I would require input to fix this, as everything turns out to be working on my devices.

**Comment by Roshi617** [comment]
Let's make this clear: can DroidRec capture the audio of let's say a game without the microphone? Or is this not implemented. I feel like there is a bit of confusion.

**Comment by yakovlevegor** [comment]
It can, the recording property is set to "media", but it doesn't even need it explicitly, it will record any Android 10+ app that allows it just fine.

**Comment by yakovlevegor** [comment]
If this issue exists right from 2.5, I am absolutely clueless.

**Comment by Roshi617** [comment]
I will try this on my old tablet. Not sure what ROM I left on it, but last I knew it was also Android 11. My phone (what I have been testing DroidRec with) is a Motorola. My tablet is Samsung

**Comment by Roshi617** [comment]
The Samsung tablet creates 0 bytes video files every time. Version 3.1. Permissions are granted, FPS set to 30, and I tried every codec.

**Comment by Roshi617** [comment]
It is running Android 11 with Magisk. Not sure it has to do with it creating 0 bytes files

**Comment by yakovlevegor** [comment]
Would it work with custom audio sample rate set to `41000`?

**Comment by Roshi617** [comment]
Nope, still not working.

**Comment by yakovlevegor** [comment]
Versions below 2.4?

**Comment by Roshi617** [comment]
I tried version 2.3 and it's still not working...

**Comment by yakovlevegor** [comment]
Nothing I can do then. Audio recording is not supported on your devices.

**Comment by Roshi617** [comment]
That's interesting, as my phone's builtin screen recorder can pickup my game's audio just fine. I am only using your app because it's not bloatware. However, I understand that you can't fix it.

**Comment by yakovlevegor** [comment]
I'll keep this issue open, just in case.

**Comment by yakovlevegor** [comment]
The final attempt. I've added every possible audio source in `AudioAttributes` configuration.
[app-soundallsources.zip](https://github.com/yakovlevegor/DroidRec/files/10243135/app-soundallsources.zip)

**Comment by Roshi617** [comment]
Nope. Unfortunately it still isn't working. Thanks for trying though. Microphone may have to do if I'm going to use your app.

**Comment by yakovlevegor** [comment]
I'm going to add an error message for that.

**Comment by yakovlevegor** [comment]
I've made a different version which will display the raw exception error message that the system is giving. Just to reassure that the error is critical.
[app-errordisplaycause.zip](https://github.com/yakovlevegor/DroidRec/files/10248269/app-errordisplaycause.zip)

**Comment by Roshi617** [comment]
Where is this error supposed to display? I'm not seeing anything anywhere.

**Comment by yakovlevegor** [comment]
Oh well, then the exception isn't even detected.

**Comment by Roshi617** [comment]
If I choose to record audio only it creates an audio file that is 24kb and has nothing in it (0 seconds length). This is honestly baffling because other screen recording apps that implement Android 10+ internal audio recording work just fine

**Comment by yakovlevegor** [comment]
Of course built-in recorders would work fine, they don't require any special system apis to record playback.

**Comment by Roshi617** [comment]
No I even mean ones on Google Play.

**Comment by yakovlevegor** [comment]
Even without root?

**Comment by Roshi617** [comment]
Yes. I cannot root my phone.

**Comment by yakovlevegor** [comment]
It's an error I can't detect. I need a debug logcat minimum.

**Comment by yakovlevegor** [comment]
Okay, this one will show the last exception message on recording stop.
[app-lastexception.zip](https://github.com/yakovlevegor/DroidRec/files/10249619/app-lastexception.zip)

**Comment by Roshi617** [comment]
I tried this one. Stopping the recording makes an empty toast notification pop up

**Comment by yakovlevegor** [comment]
Then I need a logcat.

**Comment by yakovlevegor** [comment]
This one will also display errors if there is something's wrong with `MediaMuxer`, but these are all the exceptions I can detect.
[app-moreverbose.zip](https://github.com/yakovlevegor/DroidRec/files/10250987/app-moreverbose.zip)

**Comment by Roshi617** [comment]
https://drive.google.com/file/d/19G5Sv7EyAT7OWim1baE82oalhfKEe7lJ/view?usp=drivesdk

I used an app called SysLog to grab this logcat. I had to grant access to logcat via ADB because my phone cannot be rooted. I used your "last exception" version of DroidRec. I can try with another version if you wish.

**Comment by Roshi617** [comment]
Sorry, am not familiar enough with GitHub apparently. I didn't need Google Drive lol.
[logcat.log](https://github.com/yakovlevegor/DroidRec/files/10253105/logcat.log)

**Comment by Roshi617** [comment]
This one is when I chose to record audio only.
[AudioOnly-logcat.log](https://github.com/yakovlevegor/DroidRec/files/10253118/AudioOnly-logcat.log)

**Comment by Roshi617** [comment]
The "more verbose" version of your app crashes upon stopping the recording, however the notification stays and requires a force stop to get rid of.

[moreverbose-Videologcat.log](https://github.com/yakovlevegor/DroidRec/files/10253140/moreverbose-Videologcat.log)
[moreverbose-AudioOnly.log](https://github.com/yakovlevegor/DroidRec/files/10253141/moreverbose-AudioOnly.log)

**Comment by yakovlevegor** [comment]
Thank you. Hope that way it would be much easier.

**Comment by yakovlevegor** [comment]
Unfortunately I didn't notice anything suspicious. My only lead here is the `AudioRecord` object for system audio playback doesn't get released after the recording ends(which worked for me anyway), this could potentially cause problems.
[app-releaserecord.zip](https://github.com/yakovlevegor/DroidRec/files/10253514/app-releaserecord.zip)

**Comment by Tracy-Howarth** [comment]
Hi yakovlevegor.

My apologies for the delay in replying. I'm on Android 11, and I've now upgraded to your app's latest version 3.1, but still the problem persists.

I'll clarify the problem I have. I am initially testing your app, so I attempted to capture both video and (internal) audio of a previously video screen grab I created with my another app (which incidentally works perfectly in capturing video and internal audio), i.e., there's no DRM involved.

Your app captures the video without issue, but there's no audio when attempting to grab the (internal) audio.

But when opting to capture the video's audio via microphone, it works, but as expected, the audio is no way near as clear if it were captured by internal audio.

I'll try the various builds you posted above with logging capabilities, and report back soon.

Thanks for your persistence. 👍

**Comment by Tracy-Howarth** [comment]
Hi yakovlevegor.

My apologies for the delay in replying. I'm on Android 11, and I've now upgraded to your app's latest version 3.1, but still the problem persists.

I'll clarify the problem I have. I am initially testing your app, so I attempted to capture both video and (internal) audio of a previously video screen grab I created with my another app (which incidentally works perfectly in capturing video and internal audio), i.e., there's no DRM involved.

Your app captures the video without issue, but there's no audio when attempting to grab the (internal) audio.

But when opting to capture the video's audio via microphone, it works, but as expected, the audio is no way near as clear if it were captured by internal audio.

I'll try the various builds you posted above with logging capabilities, and report back soon.

Thanks for your persistence. 👍

**Comment by Tracy-Howarth** [comment]
Hi @yakovlevegor.

My apologies for the delay in replying. I'm on Android 11, and I've now upgraded to your app's latest version 3.1, but still the problem persists.

Most of what @Roshi617 has previously written rings true for me too.

I'll clarify the problem I have. I am initially testing your app, so I attempted to capture both video and (internal) audio of a non-DRM video. Your app (v2.5 and v3.1) captures both the video stream and the output from the microphone. No problem here.

But when attempting to capture both the video stream and the (internal) audio stream, the video playback is fine, but alas no audio.

I then use another app to capture the video and (internal) audio of the same video, and it works perfectly.

So somehow your app doesn't capture the (internal) audio stream.

I'll try the various builds you posted above with logging capabilities, and report back soon.

Thanks for your persistence, @yakovlevegor. 👍

**Comment by Tracy-Howarth** [comment]
Apologies for the multiple comments and bizarrely opening/closing this thread. Something weird happened my end. Sorry.

My amended and correct comment now is present.

**Comment by Tracy-Howarth** [comment]
> Sorry, am not familiar enough with GitHub apparently. I didn't need Google Drive lol. [logcat.log](https://github.com/yakovlevegor/DroidRec/files/10253105/logcat.log)

Neither am I familiar with GitHub, hence my multiple comments and closure/reopen of this thread. 😳

**Comment by Roshi617** [comment]
"release record" version doesn't work either. I didn't record a logcat this time, but I can if you need me to.

@Tracy-Howarth can you confirm this as well?

**Comment by aha999** [comment]
Audio recording also doesn't work for me, I have an Asus Zenfone 6, official Android 11, and audio recording works, ,but when a person on the other side of the conversation starts speaking, only video is being recorded, but audio cuts off.

**Comment by yakovlevegor** [comment]
Okay folks, there goes. I've built an apk of [other person's testing app](https://github.com/HarshSinghRajawat/SystemAudioCaptureAndroid) to test Audio Playback recording support.

Here: [soundtest.zip](https://github.com/yakovlevegor/DroidRec/files/10686112/soundtest.zip)

The resulting test audio record will be in your "Music/Audio Capture" directory in mp3 format.

If your device supports it, but the app doesn't, I'm changing it. If not, then it's not supported for you.

**Comment by Roshi617** [comment]
@yakovlevegor "There was a problem parsing the package."

SAI will not install it either. "DISPLAY_NAME column is null"

**Comment by yakovlevegor** [comment]
@Roshi617 fixed, the developer forgot to export the service in AndroidManifest.xml

**Comment by yakovlevegor** [comment]
@Roshi617 and the file storage permission wasn't declared obsolete. This time I tested, should work.

**Comment by yakovlevegor** [comment]
@Roshi617 Yes, indeed. Then it could mean I screwed up `MediaCodec` conversion, as that app only saves mp3.

**Comment by yakovlevegor** [comment]
First thing I checked is maybe the buffer size differs for some codecs, so I set it to a fixed value.
Here is another build to test: [app-audbuffer-limit.zip](https://github.com/yakovlevegor/DroidRec/files/10688337/app-audbuffer-limit.zip)

**Comment by yakovlevegor** [comment]
Wait, no, that one likely won't change anything, because buffer size is limited the same for both microphone and playback. I think what I'd be looking at is maybe an integer overflow.

This test build doesn't add up noises, meaning if you record both sound and microphone, only sound will be recorded: [app-noaddup-limit.zip](https://github.com/yakovlevegor/DroidRec/files/10688387/app-noaddup-limit.zip)

**Comment by Roshi617** [comment]
@yakovlevegor noaddup-limit ACTUALLY WORKS! It did exactly as you described. Both audio and microphone boxes checked, yet nothing from the microphone was recorded. Just the game's sound! I think this might be a HUGE step towards the solution!

Let's have some people test this. @aha999 @Tracy-Howarth @sr093906

**Comment by yakovlevegor** [comment]
Whoa, didn't expect that one. Would you mind testing the one *just* with audbuffer limit to make it all clear? This is just great.

**Comment by yakovlevegor** [comment]
I think I finally get what's wrong. The buffer size that `AudioRecord` uses was doubled, which shouldn't happen as it's for both channels. Here is a build to test:  [app-buffer-size-detect-nodouble.zip](https://github.com/yakovlevegor/DroidRec/files/10693387/app-buffer-size-detect-nodouble.zip)

**Comment by Roshi617** [comment]
bufsize-correct-fixed pops up a toast notification upon screen rotation. It said there was a codec error. Then recording file that took place before the rotation is intact but after that error the recording is 0 bytes.

**Comment by yakovlevegor** [comment]
The error is that after pause the app crashes, which happened because of not double-checking the fix for #36

**Comment by yakovlevegor** [comment]
Latest build with `2048` buffer commit, pretty much the same: [app-audio-latest-buffer.zip](https://github.com/yakovlevegor/DroidRec/files/10713972/app-audio-latest-buffer.zip)

**Comment by Roshi617** [comment]
audio-latest-buffer works! Just as the app was originally intended to function. Record audio checked, record microphone unchecked. Rotation works correctly as well.

**Comment by yakovlevegor** [comment]
Thanks for double confirmation. The patch is applied, will be included in the next release.

**Comment by Roshi617** [comment]
Sounds good Egor. Thank you for all your hard work! 😄

**Comment by Roshi617** [comment]
Alrighty, sounds good.

**Comment by Roshi617** [comment]
?

**Comment by yakovlevegor** [comment]
I don't have a confirmation the matter is fixed, so this stays open for now.

**Comment by Roshi617** [comment]
Ah ok.

**Comment by yakovlevegor** [comment]
The repository migrates to GitLab, new page for your issue is: https://gitlab.com/egoroyakovlev/DroidRec/-/issues/39
