### ISSUE TITLE
Crash for constructor introduced in API 26

### ISSUE THREAD

**Issue by opk12** [yakovlevegor/DroidRec#4]
Hello, I use this app on Android 7.1 / API 25 and I have this crash in my logs. Here is a link to [Notification.NotificationBuilder](https://developer.android.com/reference/android/app/Notification.Builder#Builder(android.content.Context,%20java.lang.String)) for convenience

```
04-30 15:00:02.914 31029 31029 E AndroidRuntime: FATAL EXCEPTION: main
04-30 15:00:02.914 31029 31029 E AndroidRuntime: Process: com.yakovlevegor.DroidRec, PID: 31029
04-30 15:00:02.914 31029 31029 E AndroidRuntime: java.lang.NoSuchMethodError: No direct method <init>(Landroid/content/Context;Ljava/lang/String;)V in class Landroid/app/Notification$Builder; or its super classes (declaration of 'android.app.Notification$Builder' appears in /system/framework/framework.jar)
04-30 15:00:02.914 31029 31029 E AndroidRuntime: 	at com.yakovlevegor.DroidRec.ScreenRecorder.screenRecordingStart(ScreenRecorder.java:323)
04-30 15:00:02.914 31029 31029 E AndroidRuntime: 	at com.yakovlevegor.DroidRec.ScreenRecorder.actionStart(ScreenRecorder.java:193)
04-30 15:00:02.914 31029 31029 E AndroidRuntime: 	at com.yakovlevegor.DroidRec.ScreenRecorder.onStartCommand(ScreenRecorder.java:160)
04-30 15:00:02.914 31029 31029 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3770)
04-30 15:00:02.914 31029 31029 E AndroidRuntime: 	at android.app.ActivityThread.-wrap23(ActivityThread.java)
04-30 15:00:02.914 31029 31029 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
```

**Comment by yakovlevegor** [comment]
That means the intents submitted are correct, but are not being received along with commands.

**Comment by yakovlevegor** [comment]
I have a thought about it. If you could build the app yourself, please try it with editing `AndroidManifest.xml` and set `android:targetSdkVersion` property to **27**. The error suggests your system library doesn't have needed functionality.

**Comment by yakovlevegor** [comment]
Or if building is problematic, you could try the debug apk I've built: 
[app-build-debug.zip](https://github.com/yakovlevegor/DroidRec/files/8598384/app-build-debug.zip)

**Comment by yakovlevegor** [comment]
Okay, I confirm that building the app with Android SDK >= 29 makes it crash instead of recording.

**Comment by opk12** [comment]
`screenRecordingStart()` calls at line 374 the Notification.Builder constructor that has two arguments, which does not exist on Android < 8.

**Comment by yakovlevegor** [comment]
Thanks, will be looking into that. API 29(Android 10)+ requires some new settings on `startForeground` before `MediaProjection` creation. Already have a solution for that, will commit later. As for Android < 8 `Notification.Builder`, I'll see.

**Comment by yakovlevegor** [comment]
Yep, the old `Notification.Builder` constructor is required, but it's deprecated. I'm gonna add an if-else statement on it.

**Comment by yakovlevegor** [comment]
I think everything should work fine now. If you notice any other crashes, please report to #3, or if not, you can close it. I'm closing the issue as complete.

**Comment by opk12** [comment]
I confirm that 1.5 works on my device. Thank you!
