### ISSUE TITLE
Cannot set bitrate

### ISSUE THREAD

**Issue by QmZh** [yakovlevegor/DroidRec#42]
I cannot set custom bitrate for recording. It automatically changes back to a very large bitrate. Most times it's 2147483647, sometimes it's another number. Before it was okay. Now I encounter this problem in every version I have: 2.3 2.5 3.0 3.1.
I got the apps from F-droid and Droid-ify's F-droid repository. My phone is Android 12, MIUI 13.0.7.

**Comment by yakovlevegor** [comment]
The lowest bitrate that can be set is 128000. Values below that level are not accepted. The default bitrate is calculated automatically based on your device capabilities. It's value is completely normal.
