### ISSUE TITLE
Shake to pause/stop

### ISSUE THREAD

**Issue by yant0** [yakovlevegor/DroidRec#44]
A feature on other 3rd party screen recording softwares. Will it be possible to add this

**Comment by drogga** [comment]
@yakovlevegor Isn't this implemented already ?, should be closed I think...
[No need to reply, because once you close it, I intend to delete this comment and unsubscribe form the issue, so I don't get notified if anyone comments in this ticket in future ;)]

**Comment by yakovlevegor** [comment]
Yep, thanks to @nmu-student for implementing it. Closing.
