### ISSUE TITLE
Adjustable video resolution

### ISSUE THREAD

**Issue by tobi987** [yakovlevegor/DroidRec#45]
First: Thanks for this APP!

Is it possible to make the resolution adjustable to reduce the file size of the video recordings even further if the quality is not important for the user?

For example, in the APP HBRecorder (https://github.com/HBiSoft/HBRecorder), the following resolutions can be set:
360P, 480P, etc.
This reduces the file sizes once again very significantly if required.

**Comment by yakovlevegor** [comment]
Isn't there a quality scale in settings already? I mean, file size can belong to a bitrate instead of setting full resolution, the size will be reduced, only artifacts will appear when the image changes. Which makes me think... yep, probably should add that one.

**Comment by tobi987** [comment]
Thank you for the answer.
Reducing the bitrate is possible, but it doesn't reduce the file size nearly as much as changing the resolution.
Would be great if you could integrate the function (changing the resolution)!

**Comment by yakovlevegor** [comment]
Added resolution options with scaling ranges from 2160p down to 360p, lower resolutions (240p/144p) just don't work.
