### ISSUE TITLE
Audio Only recording, audio file corrupt?

### ISSUE THREAD

**Issue by camerondphillips** [yakovlevegor/DroidRec#47]
After recording audio only, the audio file seems to be bugging out on an intermittent basis. 

More often than not, when recording from YouTube and/or Vanced/New Pipe, the audio file that gets saved seems to be corrupted and seemingly "skips" or sounds to have sped up significantly.

Usually the first recording works fine, then subsequent recordings fail for a period in the manner described above.

**Comment by yakovlevegor** [comment]
Odd, this looks very much exactly like #36.

**Comment by camerondphillips** [comment]
> Odd, this looks very much exactly like #36.

This issue is with audio only recording, and the audio file is playable, however the audio is

**Comment by camerondphillips** [comment]
> Odd, this looks very much exactly like #36.

This issue is with audio only recordings. The resulting .M4a file is playable but sounds choppy and/or sped up, almost like a latency issue or something.

**Comment by camerondphillips** [comment]
Here is an example: https://voca.ro/13qmKpMjFjvZ

**Comment by yakovlevegor** [comment]
The problem could be with audio buffer sizes not matching. I've made a build for this cause for #39. You could try it too: [app-audbuffer-limit.zip](https://github.com/yakovlevegor/DroidRec/files/10688337/app-audbuffer-limit.zip)

**Comment by camerondphillips** [comment]
This build just seems to repeat the following message after hitting record:
![Screenshot_20230208-232903](https://user-images.githubusercontent.com/14170085/217710746-e2c48b97-25dc-4a9b-b8bc-0b2513c6256e.png)

Error: Audio Playback recording not allowed

**Comment by yakovlevegor** [comment]
Yeah, I set the buffer size wrong again, was too big.
Here: [app-buffersizefixed.zip](https://github.com/yakovlevegor/DroidRec/files/10693328/app-buffersizefixed.zip)

**Comment by camerondphillips** [comment]
Thanks, however this version appears to have the same issue, or at least shows the same error. I am on Android 13 if that is relevant.

**Comment by yakovlevegor** [comment]
Okay, then I'm returning the dynamic audio: [app-buffer-size-detect-nodouble.zip](https://github.com/yakovlevegor/DroidRec/files/10693387/app-buffer-size-detect-nodouble.zip)

**Comment by camerondphillips** [comment]
The same error on this version as well. Please let me know if there is anything else I can do to help here. 

Love the app in general, great work. The stand-alone audio recording would really be amazing if it worked consistently.

**Comment by yakovlevegor** [comment]
Okay then, I reverted the changes fully, before the commit in which I added this error: [app-fullrevert-audio.zip](https://github.com/yakovlevegor/DroidRec/files/10693506/app-fullrevert-audio.zip)

**Comment by camerondphillips** [comment]
This version (app-fullrevert-audio.zip) shows the same error, however it does not seem to repeat the error like previous versions. A 0 B audio file is generated as a result.

**Comment by yakovlevegor** [comment]
I also added many different usages to `AudioRecord` since the release. I reverted that too: [app-usage-media.zip](https://github.com/yakovlevegor/DroidRec/files/10693576/app-usage-media.zip)

**Comment by camerondphillips** [comment]
This version crashes after pressing Start Recording > Start Now

**Comment by yakovlevegor** [comment]
Does the app have audio recording permission?

**Comment by camerondphillips** [comment]
Yes, the app has audio recording permission (while using app). Yes 3.1 works perfectly fine, with the exception of this issue that is.

**Comment by yakovlevegor** [comment]
This one also reverts the buffer size to a wrong value, which was the case in the latest version: [app-bufsize-revert.zip](https://github.com/yakovlevegor/DroidRec/files/10694124/app-bufsize-revert.zip)

**Comment by yakovlevegor** [comment]
Here, the build with correct value for audio recording buffer: [app-bufsize-correct-fixed.zip](https://github.com/yakovlevegor/DroidRec/files/10694585/app-bufsize-correct-fixed.zip)

**Comment by camerondphillips** [comment]
This version no longer crashes, however the Error: Audio Playback recording not allowed returned, and is saving a 0 byte audio file.

**Comment by yakovlevegor** [comment]
Okay, so the only thing that left is maybe your device doesn't support `GAME` audio source. Gonna send a build without it ASAP.

**Comment by yakovlevegor** [comment]
Here, "source only media": [app-source-only-media.zip](https://github.com/yakovlevegor/DroidRec/files/10697119/app-source-only-media.zip)

**Comment by camerondphillips** [comment]
Thanks you. This build does in fact bring the audio recording back, however the primary issue still persist. 

There does not seem to be a pattern, the first two recordings worked well in this case, but then the continued to persist:

https://voca.ro/1bjZFoJZZFxS

**Comment by yakovlevegor** [comment]
This most likely indicates invalid audio bitrate detection. Try to set the audio bitrate value to `44100` or `48000` in settings, let me know of the results.

**Comment by camerondphillips** [comment]
I have tried adjusting to  44100 or 48000 and even lower just to test, however the issue still persists. I tried specifying the various codecs, as well as stereo/mono also.

**Comment by yakovlevegor** [comment]
Okay, I have no clue here, so I am reverting what's been in #36 just to check.
A build without audio timestamps support: [app-audio-nopause.zip](https://github.com/yakovlevegor/DroidRec/files/10697649/app-audio-nopause.zip)

**Comment by camerondphillips** [comment]
No luck on this version, the audio is recording but the same bug persists. I tried adjusting sample rates as well just in case.

**Comment by yakovlevegor** [comment]
Then there is some kind of failure with the encoding process. I'll see what I can find.

**Comment by yakovlevegor** [comment]
I checked, the audio codec was automatically searching for bitrate instead of default settings.
The build without bitrate selection: [app-audio-noautobitrate.zip](https://github.com/yakovlevegor/DroidRec/files/10697978/app-audio-noautobitrate.zip)

**Comment by camerondphillips** [comment]
This version seems to be crashing as well, after pressing Start Recording Start Now

**Comment by yakovlevegor** [comment]
I've specified the bitrate preset with a default value instead of not setting it: [app-preset-audio-bitrate.zip](https://github.com/yakovlevegor/DroidRec/files/10698712/app-preset-audio-bitrate.zip)

**Comment by camerondphillips** [comment]
The issue persists in this build as well.

**Comment by yakovlevegor** [comment]
There is also a codec profile option set, not sure if it's needed: [app-remove-profile-option.zip](https://github.com/yakovlevegor/DroidRec/files/10699479/app-remove-profile-option.zip)

**Comment by camerondphillips** [comment]
The issue still persist here. For what it's worth, it is related to audio only recording specifically as far as I know. I haven't tested video+audio

**Comment by yakovlevegor** [comment]
I just realized that the setting from #36 crashes the app after pause. I think I'm reviving it.

**Comment by yakovlevegor** [comment]
Well, no way around it as far as I can tell. I don't see any factor that could be causing it. Instead I could try to develop another encoder which will save audio in wav or mp3.

**Comment by yakovlevegor** [comment]
Could you please test the sample audio app from #39 and see if it has any artifacts as well?

**Comment by yakovlevegor** [comment]
I just noticed the timestamp is calculated based on read buffer information. I've tried to manually set the read amount to be fixed, so there's another: [app-read-fixed-amount.zip](https://github.com/yakovlevegor/DroidRec/files/10714079/app-read-fixed-amount.zip)

**Comment by camerondphillips** [comment]
I am just seeing the "Error: Audio Playback recording not allowed" on both the version from #39, as well as the app-read-fixed-amount.zip version

**Comment by yakovlevegor** [comment]
Sorry, forgot about that patch. Here: [app-read-fixed-amount-mediasource.zip](https://github.com/yakovlevegor/DroidRec/files/10714273/app-read-fixed-amount-mediasource.zip)

**Comment by camerondphillips** [comment]
I tested 8 recording with this version. The first 4 were very promising with no issues, however the issue persisted with the next 3, and the 8th recording was ok.

It seems to be slightly more reliable at least with this preliminary testing, but not sure if that is indicative of changes or just by chance.

**Comment by yakovlevegor** [comment]
I've tried substituting the timestamp calculating function for another: [app-capture-new-timestamps.zip](https://github.com/yakovlevegor/DroidRec/files/10714381/app-capture-new-timestamps.zip)

**Comment by camerondphillips** [comment]
The issue still persists here, about 50/50 with this test. I wish I had some sort of pattern or indicator for you but it seems pretty sporadic.

I can't necessarily replicate it under any specific circumstances, it seems to be rather random. Starting to wonder if maybe it is just a flaw in the MediaProjection API? Or maybe device specific? Memory? Wish I had more to give you.

**Comment by yakovlevegor** [comment]
I think you should try the sample app. If the issue persists, there's nothing I can do.

**Comment by camerondphillips** [comment]
The issue does not seem to be present in the sample app! It is a bit more difficult to test in abundance, however so far 6/6 (10-30 seconds) have recorded without issue in mp3 format

**Comment by yakovlevegor** [comment]
Good, then I'm gonna make a brand new encoder for mp3.

**Comment by yakovlevegor** [comment]
And by the way, the sample app shouldn't have worked for you, because your phone didn't support `USAGE_GAME`. That one proves the problem is in audio format.

**Comment by camerondphillips** [comment]
Interesting, it did crash a few times for what it's worth, if I didn't wait for the recording stopped notification before pressing "stop" again.

There was some delay between

**Comment by yakovlevegor** [comment]
Here's the sample app with the patch applied, just to make sure: [sample-app-nogame.zip](https://github.com/yakovlevegor/DroidRec/files/10715155/sample-app-nogame.zip)

**Comment by camerondphillips** [comment]
Confirmed the delay/crash issue does not persist with this patch. Recordings are still fine as well.

**Comment by yakovlevegor** [comment]
Then it's all gonna be settled. Thanks for testing.

**Comment by camerondphillips** [comment]
Thank you for all your hard work diagnosing this issue!

**Comment by yakovlevegor** [comment]
Well, that won't be `mp3`. The sample app actually uses `wav`, so no encoding is done, which may be the reason why you don't experience any overhead.

**Comment by yakovlevegor** [comment]
No, wrong again. The data is captured in `raw pcm` format, and only then encoded to `wav`.

**Comment by yakovlevegor** [comment]
Since Android 7.0 a functionality to receive automatic timestamps was added. I tried switching to it, just to check: [app-timestamp-automatic.zip](https://github.com/yakovlevegor/DroidRec/files/10715885/app-timestamp-automatic.zip)

**Comment by camerondphillips** [comment]
The issue still persists in this version. 2/8 recordings were afflicted in M4a format

**Comment by yakovlevegor** [comment]
I just hesitate to write raw `wav` files, because their size would be enormous. Instead I'll try specifying as many codec parameters as I can and see if stuff works.

**Comment by yakovlevegor** [comment]
This one has PCM encoding specified, also codec priority, input buffer size and bitrate: [app-new-codec-parameters.zip](https://github.com/yakovlevegor/DroidRec/files/10762504/app-new-codec-parameters.zip)

**Comment by camerondphillips** [comment]
The issue persists here, 4 in 10 recordings.

**Comment by yakovlevegor** [comment]
To be clear, the file isn't corrupt. The link you sent me was a file converted from `m4a` to `mp3`, so all headers are fine. Here is a build with video track also created for `m4a`: [app-audio-videotrack.zip](https://github.com/yakovlevegor/DroidRec/files/10776728/app-audio-videotrack.zip)

**Comment by camerondphillips** [comment]
The example I sent was converted by vocaroo, however the initial.m4a file has the same artifacts. Recordings from this version cannot be played and all have small file sizes (100-300kb)

**Comment by yakovlevegor** [comment]
Well, everything plays fine for me. It seems like `MediaMuxer` is failing you. I'll try to create a solution with a PCM buffer in RAM which collects and drains samples, but if that one won't work, your codecs are definitely broken. You can also try renaming file from `m4a` to `mp4` and try to play it, but I doubt this would change the situation.

**Comment by yakovlevegor** [comment]
For which by the way I should know, does the microphone alone record fine, or is it broken as well?

**Comment by camerondphillips** [comment]
Audio recorder via microphone shares the same issue

**Comment by yakovlevegor** [comment]
Well, then it's not related to "system audio" recording, your main "AAC" codec doesn't support writing only one audio track, as it seems. I'll try to see if I can search for other codecs for this cause.

**Comment by yakovlevegor** [comment]
Sorry, it seems I edited my last message too late. The issue you experience with microphone recording is overhead, right?

**Comment by camerondphillips** [comment]
The issue with the microphone is in the release build and has the same audio bug described originally

**Comment by yakovlevegor** [comment]
My best guess is the codec expects both video and audio to be captured, and errors when only one of the inputs is processed.

**Comment by yakovlevegor** [comment]
Turns out I have the same issues too, if recording conditions are slightly altered.

**Comment by yakovlevegor** [comment]
Turns out the codec preferences were not applied, because I forgot to update the key name. I've made a test build with additional preference to choose an audio codec. You could try it, and specify a different one.
[app-audiocodec-choose.zip](https://github.com/yakovlevegor/DroidRec/files/11079199/app-audiocodec-choose.zip)

**Comment by yakovlevegor** [comment]
Odd, because I didn't change the app signature. Here's another build: 
[app-audiocodecsettings.zip](https://github.com/yakovlevegor/DroidRec/files/11083297/app-audiocodecsettings.zip)

**Comment by yakovlevegor** [comment]
As seen in #51, others don't seem to have issues you are having. You could try to do a fresh install if there are any problems with the app.

**Comment by yakovlevegor** [comment]
The repository migrates to GitLab, new page for your issue is: https://gitlab.com/egoroyakovlev/DroidRec/-/issues/47
