### ISSUE TITLE
[Feature Request] "Open With" functionality

### ISSUE THREAD

**Issue by camerondphillips** [yakovlevegor/DroidRec#49]
Add an option in settings that would trigger "Open With" menu after pressing "stop recording" to instantly allow you to choose an application to open your newly created video or audio file with.

**Comment by yakovlevegor** [comment]
It already exists. You just need to press on the completed notification to open your newly created file in whatever way you like.

**Comment by camerondphillips** [comment]
Thanks for clarifying, I had notifications off so didn't see this option. 

That being said "Share" and "Open With" are not quite the same as some apps do not allow you "share" files to them in that manner.

**Comment by camerondphillips** [comment]
Thanks for clarifying, I had notifications off and didn't see this option.
