### ISSUE TITLE
Recording starts, but only records after 5 second has passed.

### ISSUE THREAD

**Issue by randomguyfromAustria** [yakovlevegor/DroidRec#50]
Hello,
First off, the app itself is awesome, it is simple and easy to use.
Now with the issue itself. I press on "Record", and the recording starts, but when i click on stop, the first 5 seconds are not recorded, anything after the 5 second gets recorded as a video. It somehow works flawlessly on "Legacy Advanced Engine" on ADV Screen recorder
I use a Redmi Note 10S, with PixelExperience+ 13 GSI. I tried out other codecs, none of them worked.
Please fix this issue.

**Comment by yakovlevegor** [comment]
That's a known issue. Most likely the codec errors, and then restarts for an unknown reason. I thought the delay was because of auto codec-choosing, but if you tried everything, it seems this is serious.

**Comment by yakovlevegor** [comment]
The codec settings got discarded because I messed up the preference key name. When choosing a specific codec the 5 second pause shouldn't happen.

**Comment by randomguyfromAustria** [comment]
Okay, now the issue has been fixed, but the recording is very laggy. Does that have to do something with my phone or with the app because on another screen recording app, it records smoothly?

**Comment by yakovlevegor** [comment]
Have you tried other codecs? Do they run normal?

**Comment by yakovlevegor** [comment]
If the recording is laggy, try to decrease it's quality. That's usually the issue.

**Comment by randomguyfromAustria** [comment]
> Have you tried other codecs? Do they run normal?

None of the codecs run smoothly.



> If the recording is laggy, try to decrease it's quality. That's usually the issue.

I also tried to decrease the quality, the lag still happens

**Comment by yakovlevegor** [comment]
Does setting custom FPS help?

**Comment by randomguyfromAustria** [comment]
> Does setting custom FPS help?
Sadly, it doesnt, the footage still lags

**Comment by yakovlevegor** [comment]
Could you please write your specs? The issue may require debug logs too.

**Comment by randomguyfromAustria** [comment]
> Could you please write your specs? The issue may require debug logs too.

Phone: Redmi Note 10s (Rosemary)
RAM: 6GB
CPU: Mediatek Helio G95
OS: PixelExperience+ GSI 13 (installed through fastbootd)

**Comment by yakovlevegor** [comment]
Does turning off audio recording help? There has been a similar issue with audio recording lagging.

**Comment by randomguyfromAustria** [comment]
> Does turning off audio recording help? There has been a similar issue with audio recording lagging.

The video still lags

**Comment by yakovlevegor** [comment]
Was the recording running normal when the bug persisted?

**Comment by yakovlevegor** [comment]
I've noticed the IFrame interval value was abnormal in codec settings. That *might* help solve the issue.

Here's a test build:
[app-iframe-interval-fix.zip](https://github.com/yakovlevegor/DroidRec/files/11805719/app-iframe-interval-fix.zip)

**Comment by yakovlevegor** [comment]
The repository migrates to GitLab, new page for your issue is: https://gitlab.com/egoroyakovlev/DroidRec/-/issues/50
