### ISSUE TITLE
Add monochrome icon

### ISSUE THREAD

**Issue by xmha97** [yakovlevegor/DroidRec#51]
Please support the Themed Icon.
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#user-theming

![Screenshot_2023-02-20-16-16-03-137_de.mm20.launcher2.release.jpg](https://user-images.githubusercontent.com/23485114/220112270-87ee0c70-3f22-438a-a606-6e9c8890bfd6.jpg)

Thanks.

**Comment by yakovlevegor** [comment]
Added. Here is a test build: 
[app-icon-monochrome.zip](https://github.com/yakovlevegor/DroidRec/files/11094335/app-icon-monochrome.zip)

**Comment by xmha97** [comment]
Thanks,
![Screenshot_2023-03-29-02-23-52-801_de mm20 launcher2 release](https://user-images.githubusercontent.com/23485114/228385626-d1bf4ede-a44b-4e4c-a02d-e04cfb4c1829.jpg)

But the monochrome icon is little big:
![Screenshot_2023-03-29-02-26-32-459_ru tech imageresizershrinker](https://user-images.githubusercontent.com/23485114/228385717-789bc58e-bcef-4a6e-9e8a-1da5f9886918.jpg)

**Comment by yakovlevegor** [comment]
Resized, here, the new build:
[app-icon-monochrome-resized.zip](https://github.com/yakovlevegor/DroidRec/files/11095184/app-icon-monochrome-resized.zip)

**Comment by xmha97** [comment]
Thanks, this is good. 👍

![Screenshot_2023-03-29-04-52-08-997_de.mm20.launcher2.release.jpg](https://user-images.githubusercontent.com/23485114/228402245-caee2ee3-38c5-439c-b962-12d753491f03.jpg)

**Comment by yakovlevegor** [comment]
Version [3.2](https://github.com/yakovlevegor/DroidRec/releases/tag/v3.2) is out. The fix is in the latest release.

**Comment by xmha97** [comment]
Thanks 🙏
