### ISSUE TITLE
Getting results from SAF caused error

### ISSUE THREAD

**Issue by AidosZhaqyp** [yakovlevegor/DroidRec#65]
On MIUI if you will click on "CHANGE RECORDINGS FOLDER" and do not choose any folder, back to the app by Back button it will crash.

Log:
https://pastebin.com/72UDnDMN

A solution:
Putting a null checker in onActivityResult

**Comment by yakovlevegor** [comment]
Fixed, a possible duplicate of #61. Though thanks for the hint!
