### ISSUE TITLE
[Feature request] Screen Annotation

### ISSUE THREAD

**Issue by ElsAr4e** [yakovlevegor/DroidRec#71]
It would be great if you could have a toolbar like Pensela (Desktop; Example: https://youtu.be/0lMqXwuio1I ) or the App Annotate (https://play.google.com/store/apps/details?id=com.safaorhan.muallim):

So during recording you can have

- a laser pointer
- different pens (with different colors and size)
- different shapes (also arrows)  (with different colors and size)
- text (different fonts and size and color)
- an eraser
- gif support / use own picture (and resize)
- an option to delete everything with one icon
- hotkey support

And an option that you can move the toolbar and an opt-in setting that the toolbar won't be recorded although it is visible to the user during recording

**Comment by yakovlevegor** [comment]
The repository migrates to GitLab, new page for your issue is: https://gitlab.com/egoroyakovlev/DroidRec/-/issues/71
